<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Models\{Exercise,WorkoutSet}; use Illuminate\Http\Request;
class ExerciseController extends Controller {
 public function index(Request $r){$q=Exercise::visibleTo($r->user()->id)->with(['primaryMuscleGroup','secondaryMuscleGroups'])->orderBy('name');if($s=$r->string('search')->toString())$q->where('name','like',"%$s%");if($m=$r->integer('muscle_group_id'))$q->where('primary_muscle_group_id',$m);return $q->paginate(min($r->integer('per_page',50),100));}
 public function store(Request $r){$d=$this->validateExercise($r);$e=Exercise::create($d+['user_id'=>$r->user()->id,'is_custom'=>true]);$e->secondaryMuscleGroups()->sync($d['secondary_muscle_group_ids']??[]);return response()->json(['data'=>$e->load(['primaryMuscleGroup','secondaryMuscleGroups'])],201);}
 public function show(Request $r,Exercise $exercise){$this->visible($r,$exercise);return ['data'=>$exercise->load(['primaryMuscleGroup','secondaryMuscleGroups'])];}
 public function update(Request $r,Exercise $exercise){abort_unless($exercise->user_id===$r->user()->id,403);$d=$this->validateExercise($r);$exercise->update($d);$exercise->secondaryMuscleGroups()->sync($d['secondary_muscle_group_ids']??[]);return ['data'=>$exercise->load(['primaryMuscleGroup','secondaryMuscleGroups'])];}
 public function destroy(Request $r,Exercise $exercise){abort_unless($exercise->user_id===$r->user()->id,403);$exercise->delete();return response()->noContent();}
 public function history(Request $r,Exercise $exercise){$this->visible($r,$exercise);$rows=WorkoutSet::query()->join('workout_exercises as we','we.id','=','workout_sets.workout_exercise_id')->join('workouts as w','w.id','=','we.workout_id')->where('w.user_id',$r->user()->id)->where('we.exercise_id',$exercise->id)->where('workout_sets.completed',true)->orderByDesc('w.workout_date')->orderBy('workout_sets.position')->paginate(100,['w.workout_date','workout_sets.*']);return $rows;}
 public function previous(Request $r,Exercise $exercise){$this->visible($r,$exercise);$we=\App\Models\WorkoutExercise::query()->where('exercise_id',$exercise->id)->whereHas('workout',fn($q)=>$q->where('user_id',$r->user()->id))->with(['sets'=>fn($q)=>$q->where('completed',true),'workout'])->latest('id')->first();return ['data'=>$we?['date'=>$we->workout->workout_date,'sets'=>$we->sets]:null];}
 private function visible(Request $r,Exercise $e){abort_unless($e->user_id===null||$e->user_id===$r->user()->id,404);} private function validateExercise(Request $r){return $r->validate(['name'=>'required|string|max:150','primary_muscle_group_id'=>'required|exists:muscle_groups,id','secondary_muscle_group_ids'=>'array','secondary_muscle_group_ids.*'=>'exists:muscle_groups,id','equipment'=>'required|string|max:80','tracking_type'=>'required|in:weighted_reps,bodyweight_reps,weighted_bodyweight_reps','instructions'=>'nullable|string','personal_notes'=>'nullable|string']);}
}
