<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Models\Workout; use App\Services\WorkoutSyncService; use Illuminate\Http\Request; use Illuminate\Support\Str;
class WorkoutController extends Controller {
 public function __construct(private WorkoutSyncService $sync){}
 public function index(Request $r){$q=Workout::where('user_id',$r->user()->id)->with($this->sync->relations())->orderByDesc('workout_date')->orderByDesc('started_at');if($r->filled('from'))$q->whereDate('workout_date','>=',$r->date('from'));if($r->filled('to'))$q->whereDate('workout_date','<=',$r->date('to'));if($r->filled('exercise_id'))$q->whereHas('exercises',fn($x)=>$x->where('exercise_id',$r->integer('exercise_id')));return $q->paginate(min($r->integer('per_page',20),100));}
 public function active(Request $r){$w=Workout::where('user_id',$r->user()->id)->where('status','active')->with($this->sync->relations())->latest('updated_at')->first();return ['data'=>$w];}
 public function store(Request $r){$d=$this->validateWorkout($r);$w=$this->sync->sync($r->user()->id,$d);return response()->json(['data'=>$w],201);}
 public function show(Request $r,Workout $workout){$this->own($r,$workout);return ['data'=>$workout->load($this->sync->relations())];}
 public function update(Request $r,Workout $workout){$this->own($r,$workout);$d=$this->validateWorkout($r);return ['data'=>$this->sync->sync($r->user()->id,$d,$workout)];}
 public function destroy(Request $r,Workout $workout){$this->own($r,$workout);$workout->delete();return response()->noContent();}
 public function copy(Request $r,Workout $workout){$this->own($r,$workout);$workout->load($this->sync->relations());$payload=['client_uuid'=>(string)Str::uuid(),'workout_date'=>$r->input('workout_date',now($r->user()->timezone)->toDateString()),'status'=>'active','started_at'=>now(),'notes'=>$workout->notes,'mood'=>null,'exercises'=>$workout->exercises->map(fn($we)=>['exercise_id'=>$we->exercise_id,'position'=>$we->position,'sets'=>$we->sets->map(fn($s)=>['client_uuid'=>(string)Str::uuid(),'position'=>$s->position,'set_type'=>$s->set_type,'weight_kg'=>$s->weight_kg,'bodyweight_extra_kg'=>$s->bodyweight_extra_kg,'reps'=>$s->reps,'completed'=>false,'rpe'=>null])->all()])->all()];return response()->json(['data'=>$this->sync->sync($r->user()->id,$payload)],201);}
 private function own(Request $r,Workout $w){abort_unless($w->user_id===$r->user()->id,404);} private function validateWorkout(Request $r){return $r->validate(['client_uuid'=>'required|uuid','workout_date'=>'required|date','status'=>'required|in:active,completed','started_at'=>'nullable|date','ended_at'=>'nullable|date|after_or_equal:started_at','duration_seconds'=>'nullable|integer|min:0','notes'=>'nullable|string','mood'=>'nullable|integer|between:1,5','exercises'=>'array','exercises.*.id'=>'nullable|integer','exercises.*.exercise_id'=>'required|integer','exercises.*.position'=>'required|integer|min:0','exercises.*.feeling_rating'=>'nullable|integer|between:1,5','exercises.*.feeling_notes'=>'nullable|string','exercises.*.sets'=>'array','exercises.*.sets.*.client_uuid'=>'required|uuid','exercises.*.sets.*.position'=>'required|integer|min:0','exercises.*.sets.*.set_type'=>'required|in:warmup,working','exercises.*.sets.*.weight_kg'=>'nullable|numeric|min:0|max:99999','exercises.*.sets.*.bodyweight_extra_kg'=>'nullable|numeric|min:0|max:99999','exercises.*.sets.*.reps'=>'nullable|integer|min:0|max:10000','exercises.*.sets.*.completed'=>'required|boolean','exercises.*.sets.*.rpe'=>'nullable|numeric|between:1,10']);}
}
